CREATE DATABASE `identity`;
CREATE USER `identityuser` WITH PASSWORD 'pass';
GRANT ALL PRIVILEGES ON DATABASE `identity` TO `identityuser`;

USE identity;

CREATE TABLE identity.`ACCOUNT` (
    `ID`        INT PRIMARY KEY AUTO_INCREMENT,
    `MAIL`      VARCHAR(100) NOT NULL,
    `LOGIN`     VARCHAR(30) NOT NULL,
    `PASSWORD`  VARCHAR(100) NOT NULL,
    `DATE`      DATETIME NOT NULL,
    `ACTIVE`    BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT `UQ_LOGIN` UNIQUE (`LOGIN`),
    CONSTRAINT `UQ_MAIL` UNIQUE (`MAIL`),
);