-- CREATE DATABASE IDENTITY;
-- CREATE USER identityuser WITH PASSWORD 'pass';
-- GRANT ALL PRIVILEGES ON DATABASE IDENTITY TO identityuser;

CREATE TABLE ACCOUNT (
    ID          SERIAL PRIMARY KEY,
    MAIL        VARCHAR(100) NOT NULL,
    PASSWORD    VARCHAR(100) NOT NULL,
    DATE        TIMESTAMP NOT NULL,
    ACTIVE      BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT UQ_MAIL UNIQUE (MAIL)
);